### ISSUE TITLE
infeasibility report for min-cost flow problems

### ISSUE THREAD

**Issue by benthestatistician** [josherrickson/rlemon#25]
An issue for optmatch is how the various LEMON algorithms handle infeasible problems. As discussed in [optmatch #216](https://github.com/markmfredrickson/optmatch/issues/216), it seems that the methods other than Cycle Cancelling report solutions to a modified problem when offered an infeasible one.  

I see something lower down in the man pages to these functions that suggests they may each be reporting on feasiblity, but perhaps not in a place where we've been looking.  The below is taken from the bottom of the [CapacityScaling Class Template Reference](https://lemon.cs.elte.hu/pub/doc/1.3.1/a00074.html), but an identical block also appears on the [CycleCanceling Class Template Reference](https://lemon.cs.elte.hu/pub/doc/1.3.1/a00074.html) and the references for the other two.  Does rlemon support extracting the `INFEASIBLE` field from the solved problem? If so, then we might use its value to decide whether the problem was feasible or not.  (If infeasible, we might in the immediate term return NAs, for back-consistency.  Later, once we've understood what's being returned by the algorithms that forge ahead in the face of infeasiblity, we might adjust this policy and in some cases report out a less ambitious match that the solver delivered for us.) 

<h2 class="groupheader">Member Enumeration Documentation</h2>
<div class="memdoc">
<p>Enum type containing the problem type constants that can be returned by the <a class="el" href="a00074.html#a9f51b418026d5480f76426f974567c5d">run()</a> function of the algorithm. </p>
<table class="fieldtable">
<tr><th colspan="2">Enumerator</th></tr><tr><td class="fieldname"><em><a class="anchor" id="a4c669cb1cb4d98dfea944e9ceec7d33ea2884fa43446c0cbc9c7a9b74d41d7483"></a>INFEASIBLE</em>&nbsp;</td><td class="fielddoc">
<p>The problem has no feasible solution (flow). </p>
</td></tr>
<tr><td class="fieldname"><em><a class="anchor" id="a4c669cb1cb4d98dfea944e9ceec7d33ea2579881e7c83261bc21bafb5a5c92cad"></a>OPTIMAL</em>&nbsp;</td><td class="fielddoc">
<p>The problem has optimal solution (i.e. it is feasible and bounded), and the algorithm has found optimal flow and node potentials (primal and dual solutions). </p>
</td></tr>
<tr><td class="fieldname"><em><a class="anchor" id="a4c669cb1cb4d98dfea944e9ceec7d33ea6c65123d1b5b01632a477661055b01ef"></a>UNBOUNDED</em>&nbsp;</td><td class="fielddoc">
<p>The digraph contains an arc of negative cost and infinite upper bound. It means that the objective function is unbounded on that arc, however, note that it could actually be bounded over the feasible flows, but this algroithm cannot handle these cases. </p>
</td></tr>
</table>

**Comment by benthestatistician** [comment]
I'd welcome anyone's thoughts on this, but wrote it with @josherrickson in mind.

**Comment by josherrickson** [comment]
Returning the status of the enum should be easy enough. @arav-agarwal2  or @atewari7, whenever you get a chance.

**Comment by arav-agarwal2** [comment]
I've made a PR with what I think handles the changes, #26 . Feel free to add tests / let me know how we might test this properly, and then we can pull it into master.
