### ISSUE TITLE
Increase Test Code Coverage

### ISSUE THREAD

**Issue by arav-agarwal2** [josherrickson/rlemon#8]
- [x] 100% coverage in R/
- [ ] 100% coverage in src/
- [ ] ~100% coverage in inst/~

Original goals below:

- [x]  Graph-Search
    - [x]  Bfs
    - [x]  Dfs
    - [x]  MaxCardinalitySearch
    - [x]  Check if Bfs/DfsVisit can be implemented
- [x]  Shortest Path
    - [x]  BellmanFord
    - [x]  Dijkstra
    - [x]  Suurballe
- [x]  MinimumSpanningTree
    - [x]  Kruskal
    - [x]  minCostArborescence
- [x]  MaxFlow
    - [x]  Circulation
    - [x]  EdmondsKarp
    - [x]  Preflow
- [x]  MinCostFlow
    - [x]  CapacityScaling
    - [x]  CostScaling
    - [x]  CycleCanceling
    - [x]  NetworkSimplex
- [x]  MinCut
    - [x]  HaoOrlin
    - [x]  GomoryHu
    - [x]  Nagamochilbaraki
- [x]  MinMeanCycle
    - [x]  HartmannOrlinMmc
    - [x]  HowardMmc
    - [x]  KarpMmc
- [x]  Matching
    - [x]  MaxMatching
    - [x]  MaxWeightedMatching
    - [x]  MaxWeightedPerfectMatching
    - [x]  MaxFractionalMatching
    - [x]  MaxWeightedFractionalMatching
    - [x]  MaxWeightedPerfectFractionalMatching
- [x]  Connectivity Algorithms
    - [x]  TopologicalSort
    - [x]  CheckedTopologicalSort
    - [x]  Bipartite Partitions
    - [x]  loopfree
    - [x]  parallelfree
    - [x]  simpleGraph
    - [x]  eulerian
- [x]  PlanarEmbedding and Drawing
    - [x]  PlanarEmbedding
    - [x]  PlanarDrawing
    - [x]  PlanarColoring
- [x]  TSP
    - [x]  Christosfides
    - [x]  Greedy
    - [x]  Insertion
    - [x]  NearestNeighbor
    - [x]  Opt2
- [x]  Approximation Algorithms
    - [x]  GrossoLocatelliPullan
- [x] Check graph

**Comment by arav-agarwal2** [comment]
Adding an issue here so, at the least, we want one test case per algorithm to get code coverage ~60-70%

**Comment by arav-agarwal2** [comment]
Add tests from FORTRAN to standard R, using smalltest data

**Comment by josherrickson** [comment]
Looking at some files, it seems like most of this is checked off?

- https://github.com/atewari7/rlemon/blob/5f968dcf102a86340b58ec3777dda80994d0ca4c/tests/testthat/test-shortestPath.R#L27
- https://github.com/atewari7/rlemon/blob/5f968dcf102a86340b58ec3777dda80994d0ca4c/tests/testthat/test-planarityembedding.R#L54
- https://github.com/atewari7/rlemon/blob/master/tests/testthat/test.check_graph.R

**Comment by josherrickson** [comment]
I've code-coverage against the package; please see the coverage.html file. Any insights into whether we can up that coverage?

**Comment by josherrickson** [comment]
Thanks. I just pushed up a commit expanding to cover 100% of the R/ directory. I think down the road if we could get 100% of src/ files covered, that'd be great, and whatever of inst/ we get, we get.

No rush on this.

**Comment by josherrickson** [comment]
Gonna close this; I'm happy with 100% on R/. Users will never enter src/ without first entering R/, so we can mostly test in there. We may see occasional errors in src/ that we haven't tested for, but can address those as they arrive.
